name: Test PR

on: 
  pull_request:
    branches:
    - '*'
jobs:
  test:
    name: Test PR
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: test
      run: gw clean build